/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReconciliationStatus = IDL.Variant({
  'matched' : IDL.Null,
  'missingInBooks' : IDL.Null,
  'missingIn2b' : IDL.Null,
});
export const ReconciliationRow = IDL.Record({
  'status' : ReconciliationStatus,
  'igstBook' : IDL.Float64,
  'cgst2b' : IDL.Float64,
  'invoiceNo' : IDL.Text,
  'sgstBook' : IDL.Float64,
  'invoiceDate' : IDL.Text,
  'sgst2b' : IDL.Float64,
  'igst2b' : IDL.Float64,
  'gstin' : IDL.Text,
  'taxableValue2b' : IDL.Float64,
  'cgstBook' : IDL.Float64,
  'taxableValueBook' : IDL.Float64,
});
export const ReconciliationSummary = IDL.Record({
  'matched' : IDL.Nat,
  'missingInBooks' : IDL.Nat,
  'missingIn2b' : IDL.Nat,
  'totalRecords' : IDL.Nat,
});
export const Time = IDL.Int;
export const ReconciliationSession = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'results' : IDL.Vec(ReconciliationRow),
  'summary' : ReconciliationSummary,
  'timestamp' : Time,
});
export const SessionMetadata = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'summary' : ReconciliationSummary,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'deleteSession' : IDL.Func([IDL.Text], [], []),
  'getSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReconciliationSession)],
      ['query'],
    ),
  'listSessions' : IDL.Func([], [IDL.Vec(SessionMetadata)], ['query']),
  'saveSession' : IDL.Func(
      [IDL.Text, ReconciliationSummary, IDL.Vec(ReconciliationRow)],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReconciliationStatus = IDL.Variant({
    'matched' : IDL.Null,
    'missingInBooks' : IDL.Null,
    'missingIn2b' : IDL.Null,
  });
  const ReconciliationRow = IDL.Record({
    'status' : ReconciliationStatus,
    'igstBook' : IDL.Float64,
    'cgst2b' : IDL.Float64,
    'invoiceNo' : IDL.Text,
    'sgstBook' : IDL.Float64,
    'invoiceDate' : IDL.Text,
    'sgst2b' : IDL.Float64,
    'igst2b' : IDL.Float64,
    'gstin' : IDL.Text,
    'taxableValue2b' : IDL.Float64,
    'cgstBook' : IDL.Float64,
    'taxableValueBook' : IDL.Float64,
  });
  const ReconciliationSummary = IDL.Record({
    'matched' : IDL.Nat,
    'missingInBooks' : IDL.Nat,
    'missingIn2b' : IDL.Nat,
    'totalRecords' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ReconciliationSession = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'results' : IDL.Vec(ReconciliationRow),
    'summary' : ReconciliationSummary,
    'timestamp' : Time,
  });
  const SessionMetadata = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'summary' : ReconciliationSummary,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'deleteSession' : IDL.Func([IDL.Text], [], []),
    'getSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReconciliationSession)],
        ['query'],
      ),
    'listSessions' : IDL.Func([], [IDL.Vec(SessionMetadata)], ['query']),
    'saveSession' : IDL.Func(
        [IDL.Text, ReconciliationSummary, IDL.Vec(ReconciliationRow)],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };