/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ReconciliationRow {
  'status' : ReconciliationStatus,
  'igstBook' : number,
  'cgst2b' : number,
  'invoiceNo' : string,
  'sgstBook' : number,
  'invoiceDate' : string,
  'sgst2b' : number,
  'igst2b' : number,
  'gstin' : string,
  'taxableValue2b' : number,
  'cgstBook' : number,
  'taxableValueBook' : number,
}
export interface ReconciliationSession {
  'id' : string,
  'name' : string,
  'results' : Array<ReconciliationRow>,
  'summary' : ReconciliationSummary,
  'timestamp' : Time,
}
export type ReconciliationStatus = { 'matched' : null } |
  { 'missingInBooks' : null } |
  { 'missingIn2b' : null };
export interface ReconciliationSummary {
  'matched' : bigint,
  'missingInBooks' : bigint,
  'missingIn2b' : bigint,
  'totalRecords' : bigint,
}
export interface SessionMetadata {
  'id' : string,
  'name' : string,
  'summary' : ReconciliationSummary,
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'deleteSession' : ActorMethod<[string], undefined>,
  'getSession' : ActorMethod<[string], [] | [ReconciliationSession]>,
  'listSessions' : ActorMethod<[], Array<SessionMetadata>>,
  'saveSession' : ActorMethod<
    [string, ReconciliationSummary, Array<ReconciliationRow>],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];